steps:
 # Build
 - name: gcr.io/cloud-builders/bazel:8.3.1
   args: ['run', '--define=yaspl_bootstrap=true', '//tools/web-calculator:web-calculator-push', 
          '--' , '--tag', '${SHORT_SHA}']
   id: "BazelPush-web-calculator"
 - name: gcr.io/cloud-builders/bazel:8.3.1
   args: ['run', '--define=yaspl_bootstrap=true', '//tools/doc-server:doc-server-push', 
          '--' , '--tag', '${SHORT_SHA}']
   id: "BazelPush-doc-server"
 - name: gcr.io/cloud-builders/bazel:8.3.1
   args: ['run', '--define=yaspl_bootstrap=true', '//tools/gcs-server:gcs-server-push', 
          '--' , '--tag', '${SHORT_SHA}']
   id: "BazelPush-gcs-server"

 # Push
 - name: gcr.io/cloud-builders/gcloud
   args: ['beta', 'run', 'deploy', 'web-calculator',
          '--platform', 'managed',
          '--image', 'gcr.io/$PROJECT_ID/web-calculator:${SHORT_SHA}',
          '--region', 'us-central1']
   id: "CloudRunDeploy-web-calculator"
 - name: gcr.io/cloud-builders/gcloud
   args: ['beta', 'run', 'deploy', 'doc-server',
          '--platform', 'managed',
          '--image', 'gcr.io/$PROJECT_ID/doc-server:${SHORT_SHA}',
          '--region', 'us-central1',
          '--memory', '512Mi']
   id: "CloudRunDeploy-doc-server"
 - name: gcr.io/cloud-builders/gcloud
   args: ['beta', 'run', 'deploy', 'gcs-server',
          '--platform', 'managed',
          '--image', 'gcr.io/$PROJECT_ID/gcs-server:${SHORT_SHA}',
          '--region', 'us-central1']
   id: "CloudRunDeploy-gcs-server"

timeout: 1h
