steps:
- name: gcr.io/cloud-builders/bazel
  args: ['run', '//tools/web-calculator:web-calculator', '--define=yaspl_bootstrap=true' ]
  id: "BazelBuild"
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/tools/web-calculator:web-calculator', 'gcr.io/crucial-bloom-404/web-calculator']
images: ['gcr.io/crucial-bloom-404/web-calculator']
