steps:
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--define=yaspl_bootstrap=true',
          '//tools/web-calculator:web-calculator-image',
          '//tools/doc-server:doc-server-image']
  id: "BazelBuild"
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/tools/web-calculator:web-calculator-image',
         'gcr.io/$PROJECT_ID/web-calculator:$SHORT_SHA']
  id: "DockerTag-web-calculator"
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/tools/doc-server:doc-server-image',
         'gcr.io/$PROJECT_ID/doc-server:$SHORT_SHA']
  id: "DockerTag-doc-server"
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/web-calculator:$SHORT_SHA']
  id: "DockerPush-web-calculator"
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/doc-server:$SHORT_SHA']
  id: "DockerPush-doc-server"
- name: gcr.io/cloud-builders/gcloud
  args: ['beta', 'run', 'deploy', 'web-calculator',
         '--image', 'gcr.io/$PROJECT_ID/web-calculator:${SHORT_SHA}',
         '--region', 'us-central1']
  id: "CloudRunDeploy-wed-calculator"
- name: gcr.io/cloud-builders/gcloud
  args: ['beta', 'run', 'deploy', 'doc-server',
         '--image', 'gcr.io/$PROJECT_ID/doc-server:${SHORT_SHA}',
         '--region', 'us-central1']
  id: "CloudRunDeploy-doc-server"
