steps:
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--define=yaspl_bootstrap=true', '//tools/web-calculator:web-calculator-image']
  id: "BazelRun-web-calculator"
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--define=yaspl_bootstrap=true', '//tools/doc-server:doc-server-image']
  id: "BazelRun-doc-server"
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--define=yaspl_bootstrap=true', '//tools/gcs-server:gcs-server-image']
  id: "BazelRun-gcs-server"
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/tools/web-calculator:web-calculator-image',
         'gcr.io/$PROJECT_ID/web-calculator:$SHORT_SHA']
  id: "DockerTag-web-calculator"
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/tools/doc-server:doc-server-image',
         'gcr.io/$PROJECT_ID/doc-server:$SHORT_SHA']
  id: "DockerTag-doc-server"
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/tools/gcs-server:gcs-server-image',
         'gcr.io/$PROJECT_ID/gcs-server:$SHORT_SHA']
  id: "DockerTag-gcs-server"
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/web-calculator:$SHORT_SHA']
  id: "DockerPush-web-calculator"
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/doc-server:$SHORT_SHA']
  id: "DockerPush-doc-server"
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/gcs-server:$SHORT_SHA']
  id: "DockerPush-gcs-server"
- name: gcr.io/cloud-builders/gcloud
  args: ['beta', 'run', 'deploy', 'web-calculator',
         '--platform', 'managed',
         '--image', 'gcr.io/$PROJECT_ID/web-calculator:${SHORT_SHA}',
         '--region', 'us-central1']
  id: "CloudRunDeploy-web-calculator"
- name: gcr.io/cloud-builders/gcloud
  args: ['beta', 'run', 'deploy', 'doc-server',
         '--platform', 'managed',
         '--image', 'gcr.io/$PROJECT_ID/doc-server:${SHORT_SHA}',
         '--region', 'us-central1',
         '--memory', '512Mi']
  id: "CloudRunDeploy-doc-server"
- name: gcr.io/cloud-builders/gcloud
  args: ['beta', 'run', 'deploy', 'gcs-server',
         '--platform', 'managed',
         '--image', 'gcr.io/$PROJECT_ID/gcs-server:${SHORT_SHA}',
         '--region', 'us-central1']
  id: "CloudRunDeploy-gcs-server"

timeout: 1h
