steps:
- name: gcr.io/cloud-builders/bazel
  args: ['run', '//tools/web-calculator:web-calculator-image', '--define=yaspl_bootstrap=true' ]
  id: "BazelBuild"
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/tools/web-calculator:web-calculator-image',
         'gcr.io/$PROJECT_ID/web-calculator:$SHORT_SHA']
  id: "DockerTag"
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/web-calculator:$SHORT_SHA']
  id: "DockerPush"
- name: gcr.io/cloud-builders/gcloud
  args: ['beta', 'run', 'deploy', 'web-calculator',
         '--image', 'gcr.io/$PROJECT_ID/web-calculator:${SHORT_SHA}',
         '--region', 'us-central1']
