package(
    default_visibility = ["//visibility:public"],
)

config_setting(
    name = "darwin",
    values = {
        "cpu": "darwin",
    },
)

config_setting(
    name = "linux_x86_64",
    values = {
        "cpu": "k8",
    },
)

config_setting(
    name = "host_and_target_linux_x86_64",
    values = {
        "cpu": "k8",
        "host_cpu": "k8",
    },
)

config_setting(
    name = "host_and_target_darwin",
    values = {
        "cpu": "darwin",
        "host_cpu": "darwin",
    },
)
