os:
 - osx
osx_image: xcode7.3

before_install:
  - wget "https://github.com/bazelbuild/bazel/releases/download/0.2.2b/bazel-0.2.2b-installer-darwin-x86_64.sh"
  - shasum -c travis/bazel-0.2.2b-installer-darwin-x86_64.sh.sha256
  - chmod u+x bazel-0.2.2b-installer-darwin-x86_64.sh
  - ./bazel-0.2.2b-installer-darwin-x86_64.sh --user
  - brew update
  - brew outdated py7zip || brew install p7zip


install: true
script: bazel test --keep_going //...
