language: generic
matrix:
  include:
    - os: osx
      osx_image: xcode9.3
    - os: linux
      dist: xenial
      compiler: clang

before_install:
  - as --version
  # OS X setup
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget "https://github.com/bazelbuild/bazel/releases/download/0.28.1/bazel-0.28.1-installer-darwin-x86_64.sh"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shasum -c travis/bazel-0.28.1-installer-darwin-x86_64.sh.sha256; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod u+x bazel-0.28.1-installer-darwin-x86_64.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./bazel-0.28.1-installer-darwin-x86_64.sh --user; fi
  # Linux setup
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget "https://github.com/bazelbuild/bazel/releases/download/0.28.1/bazel-0.28.1-installer-linux-x86_64.sh"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then shasum -c travis/bazel-0.28.1-installer-linux-x86_64.sh.sha256; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod u+x bazel-0.28.1-installer-linux-x86_64.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./bazel-0.28.1-installer-linux-x86_64.sh --user; fi

install: true
script: >
  bazel test --keep_going --define yaspl_bootstrap=true
  --host_force_python=PY2
  //...
