os:
 - osx
osx_image: xcode7.3

before_install:
  - wget "https://github.com/bazelbuild/bazel/releases/download/0.5.4/bazel-0.5.4-installer-darwin-x86_64.sh"
  - shasum -c travis/bazel-0.5.4-installer-darwin-x86_64.sh.sha256
  - chmod u+x bazel-0.5.4-installer-darwin-x86_64.sh
  - ./bazel-0.5.4-installer-darwin-x86_64.sh --user

install: true
script: bazel test --keep_going --define yaspl_bootstrap=true //...
