bazel_dep(name = "rules_pkg", version = "1.2.0")
bazel_dep(name = "rules_oci", version = "2.2.7")
bazel_dep(name = "rules_python", version = "1.9.0")
bazel_dep(name = "platforms", version = "1.0.0")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(python_version = "3.11", is_default = True, ignore_root_user_error = True)

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_archive(
  name = "minimal_racket",
  integrity = "sha256-zZAl2LiKqu15JOB8dJcw4utb+glCpFhrz6B5sTGBafw=",
  strip_prefix = "minimal-racket-60d7b3d63670b579f22ae2745086ebb03efe4b8e",
  urls = ["https://github.com/endobson/minimal-racket/archive/60d7b3d63670b579f22ae2745086ebb03efe4b8e.tar.gz"]
)

http_file(
  name = "racket_minimal_x86_64_9_1_linux",
  urls = ["https://download.racket-lang.org/releases/9.1/installers/racket-minimal-9.1-x86_64-linux-buster-cs.tgz"],
  integrity = "sha256-vVY+O5ZNs0G8QYdYia3aqNh1UuS/YrTlDHVuWm8aPVA="
)

register_toolchains(
    '//libraries/core-language:osx_core_language_toolchain',
    '//libraries/core-language:linux_core_language_toolchain',
    '//libraries/core-language:yasplos_core_language_toolchain',
)
register_toolchains(
    '//libraries/prim-language:osx_prim_language_toolchain',
    '//libraries/prim-language:linux_prim_language_toolchain',
)
register_toolchains(
    '//libraries/yaspl:osx_yaspl_toolchain',
    '//libraries/yaspl:linux_yaspl_toolchain',
    '//libraries/yaspl:yasplos_yaspl_toolchain',
)

register_toolchains(
    '@minimal_racket//:osx_racket_bootstrap_toolchain',
    '@minimal_racket//:linux_racket_bootstrap_toolchain',
    '@minimal_racket//:osx_osx_racket_toolchain',
    '@minimal_racket//:linux_linux_racket_toolchain',
    '@minimal_racket//:osx_linux_racket_toolchain',
    '@minimal_racket//:linux_osx_racket_toolchain',
)


http_file(
  name = "ovmf_code",
  sha256 = "81ede7af3351a1710a4d4a35655fac10bedb11ae3484ae785820803a5bf69829",
  urls = ["https://github.com/clearlinux/common/raw/9749d00c562b5852eb192567335f82eca434c4be/OVMF_CODE.fd"],
)
http_file(
  name = "ovmf_vars",
  sha256 = "5d2ac383371b408398accee7ec27c8c09ea5b74a0de0ceea6513388b15be5d1e",
  urls = ["https://github.com/clearlinux/common/raw/9749d00c562b5852eb192567335f82eca434c4be/OVMF_VARS.fd"],
)
